### ISSUE TITLE
Rare aspect ratios UI fix

### ISSUE THREAD

**Issue by PunishedFiddle** [kobraworksmodding/Saints-Row-2-Juiced-Patch#13]
Hi! It seems that SR2 can't properly scale its UI to 3:2 resolutions like 3840x2560 even with this patch. 
![Image](https://github.com/user-attachments/assets/7eb635f1-1ebd-439a-b435-caad00a028cc)

**Comment by Clippy95** [comment]
Disable SR2 Ultrawide in the ini and IVRadarScaling, that's the cause not the game.

**Comment by PunishedFiddle** [comment]
> Disable SR2 Ultrawide in the ini and IVRadarScaling, that's the cause not the game.

You mean:
FixUltrawideFOV=0
FixUltrawideCutsceneFOV=0
IVRadarScaling=0

If so, it didn't make any difference. I don't see any other options related to Ultrawide. Same thing on lite and full version of the patch.

![Image](https://github.com/user-attachments/assets/335a82ea-bc2d-427f-a6f2-c2e0a28a819c)

**Comment by Clippy95** [comment]
FixUltrawideHUD=0 under [Graphics] if it doesn't exist create it

**Comment by Clippy95** [comment]
Okay wait, I've just tried it myself I've just assumed that MY fix is the cause, but it seems like the game straight up doesn't support 3:2 even in vanilla?

**Comment by PunishedFiddle** [comment]
Yeah, vanilla can't recognize it , so I force it through Gibbed SR2 Resolution. I remember that I had same problem with It even before Ultrawide hud fix was included in recent update, I used 7.3.3 Juiced then.

**Comment by Clippy95** [comment]
[DFEngine.zip](https://github.com/user-attachments/files/19797425/DFEngine.zip)
Could you try this? hardcoded-ish a fix

**Comment by PunishedFiddle** [comment]
For 3840x2560 It seems to me that UI is on its place now, but feels a little bit stretched and FOV is too narrow on foot
![Image](https://github.com/user-attachments/assets/c7eaea3f-7179-423f-9d37-cf3d22648d9c)

**Comment by Clippy95** [comment]
> For 3840x2560 It seems to me that UI is on its place now, but feels a little bit stretched and FOV is too narrow on foot ![Image](https://github.com/user-attachments/assets/c7eaea3f-7179-423f-9d37-cf3d22648d9c)

The UI will probably be stretched sorry, no plan to fix that, use the FOV multiplier binds/config to increase it.

**Comment by PunishedFiddle** [comment]
Not a big deal, since It's not very stretched, but I can't change FOV at all, even through juiced.ini. Others shortcuts are working.

**Comment by Clippy95** [comment]
> Not a big deal, since It's not very stretched, but I can't change FOV at all, even through juiced.ini. Others shortcuts are working.

Oh right the FOV multiplier is for the 4:3->16:9 multiplier the game has, I'll find a solution

**Comment by Clippy95** [comment]
> Not a big deal, since It's not very stretched, but I can't change FOV at all, even through juiced.ini. Others shortcuts are working.

[DFEngine.zip](https://github.com/user-attachments/files/19801298/DFEngine.zip)

Could you try this? cutscene FOV isn't changeable and that's on purpose, I don't think it make sense to change it with the FOV multiplier, this refactor even fixes Activity FOV on ultrawide

**Comment by PunishedFiddle** [comment]
Thanks! FOV works now, but subtitles for long sentences and some UI elements are cropped off screen. Everything else seems normal

![Image](https://github.com/user-attachments/assets/169b7152-f761-41b5-9d5c-3ecbf868f260)
![Image](https://github.com/user-attachments/assets/85a720d9-09c1-435e-9970-5212e506465b)

**Comment by Clippy95** [comment]
> Thanks! FOV works now, but subtitles for long sentences and some UI elements are cropped off screen. Everything else seems normal
> 
> ![Image](https://github.com/user-attachments/assets/169b7152-f761-41b5-9d5c-3ecbf868f260) ![Image](https://github.com/user-attachments/assets/85a720d9-09c1-435e-9970-5212e506465b)

Odd it seems like it's triggering r_is_widescreen, even though I hardcoded 3:2 to be not widescreen, I'll see.

**Comment by Clippy95** [comment]
Right it wasn't that, but rather a check done by XTBL parsing, if aspectratio > 1.45 then aspectratio is widescreen, and it set the 16:9 values for some items on the screen, this is code from SR1 and is still used in SRIV I believe, either ways it should be fixed under FixUltrawideHUD
it does 1.55 now

[DFEngine.zip](https://github.com/user-attachments/files/19813108/DFEngine.zip)

**Comment by PunishedFiddle** [comment]
Thank you again! I think it works with no real issues now

**Comment by monzonit3** [comment]
<img width="956" height="596" alt="Image" src="https://github.com/user-attachments/assets/c8908033-c896-43af-9e6d-50ce6d97229d" />

<img width="958" height="597" alt="Image" src="https://github.com/user-attachments/assets/bb968fee-6019-4721-b098-bc04bb65ecf9" />

HUD seems still broken at non 16:9 resolutions eg 960x600

**Comment by Clippy95** [comment]
> <img alt="Image" width="956" height="596" src="https://private-user-images.githubusercontent.com/214870521/605887596-c8908033-c896-43af-9e6d-50ce6d97229d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODExMDcwNDcsIm5iZiI6MTc4MTEwNjc0NywicGF0aCI6Ii8yMTQ4NzA1MjEvNjA1ODg3NTk2LWM4OTA4MDMzLWM4OTYtNDNhZi05ZTZkLTUwY2U2ZDk3MjI5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYxMFQxNTUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2JjZDU5MWI0ZGQ1ZmExZDg1MjlkNTkxMGRiMWY3ZTVmMWM3NzZmZmUwNDBjY2Q0YTEwMjU5ZWI4YjI0NjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Vu8lnc_Wv0gQc0d2Ir9n8fVE6IgsgTVNHm2B_d9NcVw"> <img alt="Image" width="958" height="597" src="https://private-user-images.githubusercontent.com/214870521/605888526-bb968fee-6019-4721-b098-bc04bb65ecf9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODExMDcwNDcsIm5iZiI6MTc4MTEwNjc0NywicGF0aCI6Ii8yMTQ4NzA1MjEvNjA1ODg4NTI2LWJiOTY4ZmVlLTYwMTktNDcyMS1iMDk4LWJjMDRiYjY1ZWNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYxMFQxNTUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWNjZmNmYzhlZjRkN2YyOWUyOTBkZjU4NjRkMzY1YzgwNWIzNDEwOTI4ODdiYzA4ZTQ3M2FlYmE1MjBkMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.mAJplw7ACHz-l0wkeVYcAfSt4vDvEZZjyEHwMi1AWUw">
> 
> HUD seems still broken at non 16:9 resolutions eg 960x600

https://github.com/kobraworksmodding/Saints-Row-2-Juiced-Patch/issues/67

**Comment by monzonit3** [comment]
> > <img alt="Image" width="956" height="596" src="https://private-user-images.githubusercontent.com/214870521/605887596-c8908033-c896-43af-9e6d-50ce6d97229d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODExMDcwNDcsIm5iZiI6MTc4MTEwNjc0NywicGF0aCI6Ii8yMTQ4NzA1MjEvNjA1ODg3NTk2LWM4OTA4MDMzLWM4OTYtNDNhZi05ZTZkLTUwY2U2ZDk3MjI5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYxMFQxNTUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2JjZDU5MWI0ZGQ1ZmExZDg1MjlkNTkxMGRiMWY3ZTVmMWM3NzZmZmUwNDBjY2Q0YTEwMjU5ZWI4YjI0NjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Vu8lnc_Wv0gQc0d2Ir9n8fVE6IgsgTVNHm2B_d9NcVw"> <img alt="Image" width="958" height="597" src="https://private-user-images.githubusercontent.com/214870521/605888526-bb968fee-6019-4721-b098-bc04bb65ecf9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODExMDcwNDcsIm5iZiI6MTc4MTEwNjc0NywicGF0aCI6Ii8yMTQ4NzA1MjEvNjA1ODg4NTI2LWJiOTY4ZmVlLTYwMTktNDcyMS1iMDk4LWJjMDRiYjY1ZWNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYxMFQxNTUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWNjZmNmYzhlZjRkN2YyOWUyOTBkZjU4NjRkMzY1YzgwNWIzNDEwOTI4ODdiYzA4ZTQ3M2FlYmE1MjBkMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.mAJplw7ACHz-l0wkeVYcAfSt4vDvEZZjyEHwMi1AWUw">
> > HUD seems still broken at non 16:9 resolutions eg 960x600
> 
> [#67](https://github.com/kobraworksmodding/Saints-Row-2-Juiced-Patch/issues/67)

sorry for the duplicate
